# -*- coding: utf-8 -*-
"""Healthcare_Data_Analyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CAZZZhxtISL_JtEp3QWdLTC2pQgoMBe
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")      #For Nice Backgrounds
sns.set_context("talk")      #For slighty larger fonts

file_path = "/content/Hospital_Antibiotic_Resistance.xlsx"
sheets=pd.read_excel(file_path,sheet_name=None)
patient_df=sheets["Patient_Info"]
specimen_df=sheets["Specimen_Tests"]
bacteria_df=sheets["Bacteria_Isolates"]
antibiotic_df=sheets["Antibiotic_Resistance"]

# Step1 : Merge Patient_Info with Specimen_Tests

merged_1=pd.merge(specimen_df,patient_df,on="patient_id",how="left")

# Step2: Merge with Bacteria_Isolates

merged_2 = pd.merge(bacteria_df, merged_1, on="specimen_id", how="left")

# Step3: Merge with Antibiotic_Resistance

final_df = pd.merge(antibiotic_df, merged_2, on="isolate_id", how="left")

# Check Results:

final_df.head()

# Bacteria Frequency

plt.figure(figsize=(10,6))
sns.countplot(y="bacteria_name",data=final_df,order=final_df["bacteria_name"].value_counts().index)
plt.title("Frequency of Bacteria Isolates")
plt.xlabel("Count")
plt.ylabel("Bacteria Name")
plt.savefig("bacteria_frequency.png", dpi=300, bbox_inches="tight")
plt.show()

resistance_rate=(final_df.groupby("antibiotic_name")["sensitivity"].apply(lambda x:(x=="R").mean()*100).reset_index().rename(columns={"sensitivity":"resistance_rate"}))

# Antibiotic Resistance Rate

plt.figure(figsize=(10,6))
resistance_rate=resistance_rate.sort_values(by="resistance_rate",ascending=False)
sns.barplot(x="resistance_rate",y="antibiotic_name",data=resistance_rate)
plt.title("Antibiotic Resistance Rates (%)")
plt.xlabel("Resistance (%)")
plt.ylabel("Antibiotic")
plt.savefig("Antibiotic Resistance Rate.png", dpi=300, bbox_inches="tight")

plt.show()

# Age Distribution of Infected

plt.figure(figsize=(8,6))
sns.histplot(final_df["age"],bins=15,kde=True)
mean_age=final_df["age"].mean()
median_age=final_df["age"].median()
plt.axvline(mean_age,color="red",linestyle="--",label=f'Mean: {mean_age:.1f}')
plt.axvline(median_age,color="green",linestyle="-.",label=f'Median: {median_age:.1f}')
plt.title("Age Distribution of Infected Patients")
plt.xlabel("Age")
plt.ylabel("Count")
plt.legend()
plt.tight_layout()

plt.savefig('''Age Distribution of Infected
.png''', dpi=300, bbox_inches="tight")


plt.show()

from google.colab import files
files.download("bacteria_frequency.png")

files.download("Antibiotic Resistance Rate.png")

files.download('''Age Distribution of Infected
.png''')

bins = [0, 18, 30, 45, 60, 100]
labels = ['0-18','19-30','31-45','46-60','60+']
final_df['Age_Group'] = pd.cut(final_df['age'], bins=bins, labels=labels, right=True)

age_resistance = (
    final_df.groupby('Age_Group')['sensitivity']
    .apply(lambda x: (x == 'R').mean() * 100)
    .reset_index(name='Resistance_Rate')
)

age_counts = final_df.groupby('Age_Group').size().reset_index(name='N_tests')
age_resistance = age_resistance.merge(age_counts, on='Age_Group')

# Plot Resistance vs Age Group (line plot)
plt.figure(figsize=(8,5))
sns.lineplot(data=age_resistance, x='Age_Group', y='Resistance_Rate', marker='o')
for i, row in age_resistance.iterrows():
    plt.text(i, row['Resistance_Rate']+0.5, f"{row['Resistance_Rate']:.1f}%", ha='center', fontsize=10)
plt.title('Antibiotic Resistance Rate by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Resistance Rate (%)')
plt.ylim(0, max(age_resistance['Resistance_Rate'].max()*1.15, 10))
plt.tight_layout()
plt.savefig('age_vs_resistance.png', dpi=300, bbox_inches='tight')
plt.show()

site_resistance = (
    final_df.groupby('infection_site')['sensitivity']
    .apply(lambda x: (x == 'R').mean() * 100)
    .reset_index(name='Resistance_Rate')
)

site_counts = final_df.groupby('infection_site').size().reset_index(name='N_tests')
site_resistance = site_resistance.merge(site_counts, on='infection_site').sort_values('Resistance_Rate', ascending=False)

plt.figure(figsize=(9,5))
sns.barplot(data=site_resistance, x='Resistance_Rate', y='infection_site', palette='coolwarm')
for i, row in site_resistance.iterrows():
    plt.text(row['Resistance_Rate']+0.4, i, f"{row['Resistance_Rate']:.1f}%  (n={int(row['N_tests'])})", va='center')
plt.title('Resistance Rate by Infection Site')
plt.xlabel('Resistance Rate (%)')
plt.ylabel('Infection Site')
plt.xlim(0, site_resistance['Resistance_Rate'].max()*1.15)
plt.tight_layout()
plt.savefig('site_vs_resistance.png', dpi=300, bbox_inches='tight')
plt.show()

pivot = final_df[final_df['sensitivity']=='R'].pivot_table(index='Age_Group', columns='infection_site', values='isolate_id', aggfunc='count', fill_value=0)
# convert counts into % of tests in that age_group (if you want)
age_group_totals = final_df.groupby('Age_Group').size()
pivot_pct = pivot.div(age_group_totals, axis=0) * 100

plt.figure(figsize=(10,4))
sns.heatmap(pivot_pct, annot=True, fmt=".1f", cmap='Reds')
plt.title('Percent of Isolates that are Resistant by Age Group & Infection Site')
plt.xlabel('Infection Site')
plt.ylabel('Age Group')
plt.tight_layout()
plt.savefig('heatmap_age_site_resistance.png', dpi=300, bbox_inches='tight')
plt.show()

from scipy.stats import chi2_contingency

# build contingency: Age_Group x Resistant(Y/N)
final_df['Resistant_flag'] = final_df['sensitivity'] == 'R'
contingency = pd.crosstab(final_df['Age_Group'], final_df['Resistant_flag'])
chi2, p, dof, ex = chi2_contingency(contingency)
print("Chi2:", chi2, "p-value:", p)

