# -*- coding: utf-8 -*-
"""Logistic regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AbbHB_3sT5A2SzIGp1hrZSnfEBYGSRGj
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

file_path = "/content/Hospital_Antibiotic_Resistance.xlsx"
sheets=pd.read_excel(file_path,sheet_name=None)
patient_df=sheets["Patient_Info"]
specimen_df=sheets["Specimen_Tests"]
bacteria_df=sheets["Bacteria_Isolates"]
antibiotic_df=sheets["Antibiotic_Resistance"]

# Step1 : Merge Patient_Info with Specimen_Tests

merged_1=pd.merge(specimen_df,patient_df,on="patient_id",how="left")

# Step2: Merge with Bacteria_Isolates

merged_2 = pd.merge(bacteria_df, merged_1, on="specimen_id", how="left")

# Step3: Merge with Antibiotic_Resistance

final_df = pd.merge(antibiotic_df, merged_2, on="isolate_id", how="left")

# Check Results:

final_df.head()

final_df = final_df[final_df['sensitivity'].isin(['R','S','I'])]

final_df['resistance'] = final_df['sensitivity'].map({
    'R': 1,
    'S': 0,
    'I': 0
})

le_bacteria = LabelEncoder()
le_site = LabelEncoder()
le_antibiotic = LabelEncoder()

final_df['Bacteria_Code'] = le_bacteria.fit_transform(final_df['bacteria_name'])
final_df['Site_Code'] = le_site.fit_transform(final_df['infection_site'])
final_df['Antibiotic_Code'] = le_antibiotic.fit_transform(final_df['antibiotic_name'])

X = final_df[['age', 'Bacteria_Code', 'Site_Code', 'Antibiotic_Code']]
y = final_df['resistance']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LogisticRegression(max_iter=1000,class_weight='balanced')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

print(classification_report(y_test, y_pred))

